### ISSUE TITLE
add Tower of Hanoi 

### ISSUE THREAD

**Issue by Sejal-16** [PCCoE-Hacktoberfest-21/Data-Structures-and-Algorithms#22]
Add code for tower of hanoi in cpp

**Comment by Sejal-16** [comment]
Can i work on this ? Can you assign it to me

**Comment by Vedantnerkar** [comment]
@Sejal-16 go ahead!

**Comment by Mayankjha997** [comment]
Hello @Vedantnerkar ;
I want to contribute in Python  please assign this issue to me.

**Comment by NidhiNivedita6** [comment]
Could you please assign this to me @Vedantnerkar  ? I would like to add the code in JAVA.
